samples_file:
    "code/snakemake/20210203/config/samples.csv"
training_samples_file:
    "code/snakemake/20210203/config/samples_pass_3_training.csv"
input_dir:
    "/nfs/ftp/private/indigene_ftp/upload/OMR_Risa/20210225-0301"
training_dir:
    "/hps/research1/birney/users/ian/opto_res/ilastik/training/20210306/pass_3"
extract_frames_script:
    "scripts/extract_frames.R"
output_dir:
    "/hps/research1/birney/users/ian/opto_res/videos/20210203"
plots_dir:
    "plots/20210203/lane_demarcations"
r_container:
    "../sing_conts/baseR.sif"
plot_lanes_script:
    "scripts/plot_lanes.R"
fiji:
    "/nfs/software/birney/Fiji.app/ImageJ-linux64"
convert_to_h5_script:
    "code/snakemake/20210203/scripts/convert_tif_to_h5.ijm"
pass_dir:
    "/hps/research1/birney/users/ian/opto_res/videos/20210203/pass_3"
ilastik_container:
    "../sing_conts/Ilastik.sif"
ilastik_run:
    "/ilastik-release/run_ilastik.sh"
ilastik_project_pixclass:
    "../ilastik/projects/20210107_test_pixclass.ilp"
ilastik_project_anitrack:
    "../ilastik/projects/20210107_test_anitrack.ilp"
training_results_dir:
    "/hps/research1/birney/users/ian/opto_res/ilastik/training/20210306/results/pass_3/raw"
extract_columns_script:
    "scripts/extract_columns.R"
full_results_out:
    "data/tracking/20210203/pass_3"
