samples_file:
    "code/snakemake/20210203/config/samples.csv"
input_dir:
    "/nfs/ftp/private/indigene_ftp/upload/OMR_Risa/20210225-0301"
training_dir:
    "/hps/research1/birney/users/ian/opto_res/ilastik/training/20210306"
extract_frames_script:
    "scripts/extract_frames.R"
output_dir:
    "/hps/research1/birney/users/ian/opto_res/videos/20210203"
r_container:
    "../sing_conts/baseR.sif"
fiji:
    "/nfs/software/birney/Fiji.app/ImageJ-linux64"
convert_to_h5_script:
    "code/snakemake/20210203/scripts/convert_tif_to_h5.ijm"
ilastik_container:
    "../sing_conts/Ilastik.sif"
ilastik_run:
    "/ilastik-release/run_ilastik.sh"
ilastik_project_pixclass:
    "../ilastik/projects/20210107_test_pixclass.ilp"
ilastik_project_anitrack:
    "../ilastik/projects/20210107_test_anitrack.ilp"
training_results_dir:
    "/hps/research1/birney/users/ian/opto_res/ilastik/training/20210306/results/pass_1/raw"
full_results_dir:
    "/hps/research1/birney/users/ian/opto_res/videos/20210203/results/pass_1/raw"
extract_columns_script:
    "scripts/extract_columns.R"
full_results_out:
    "data/tracking/20210203/pass_1"
