# Bash script to run on EBI cluster:
#
# cd /hps/research1/birney/users/ian/opto_res/cos_opto_res
# conda activate snakemake
# snakemake \
#   --jobs 5000 \
#   --latency-wait 100 \
#   --cluster-config code/snakemake/20210203/config/cluster.json \
#   --cluster 'bsub -g /snakemake_bgenie -J {cluster.name} -n {cluster.n} -M {cluster.memory} -o {cluster.output} -e {cluster.error}' \
#   --keep-going \
#   --rerun-incomplete \
#   --use-conda \
#   --use-singularity \
#   -s code/snakemake/20210203/Snakefile \
#   -p

# import functions and packages
from os.path import join
import pandas as pd

# Load config file and provide content as config object

configfile: "code/snakemake/20210316/config/config.yaml"

# Load samples to process

#SAMPLES, = glob_wildcards(join(config["output_dir"], "raw/{sample}.tif"))
SAMPLES = pd.read_csv(config["samples_file"], comment="#", skip_blank_lines=True, sep=",", index_col=0)

# Rules

rule all:
    input:
        expand(join(config["output_dir"], "tifs", "{sample}.ome.tif"),
            sample = SAMPLES.index)

# Need to copy videos to working directory because Singularity can't access /nfs/ftp/private
rule copy_to_wd:
    input:
        join(config["input_dir"], "{sample}.ome.tif")
    output:
        join(config["output_dir"], "tifs", "{sample}.ome.tif")
    shell:
        "cp {input} {output}"

# Convert from TIF to AVI
rule tif2avi:
    input:
        join(config["output_dir"], "tifs", "{sample}.ome.tif")
    output:
        join(config["output_dir"], "avis", "{sample}.avi")
    singularity:
        config["r-base"]
    script:
        config["tif2avi_script"]
