samples_file:
    "code/snakemake/20210316/config/samples.csv"
input_dir:
    "/nfs/ftp/private/indigene_ftp/upload/OMR_Risa"
output_dir:
    "/hps/research1/birney/users/ian/opto_res/videos/20210316"
r-base:
    "../sing_conts/r-base.4.0.5.sif"
tif2avi_script:
    "scripts/20210414_tif2avi.R"

